### ISSUE TITLE
This "prompt" pops up at intervals as a command

### ISSUE THREAD

**Issue by Bushraven** [RatherRude/Elite-Dangerous-AI-Integration#12]
https://github.com/RatherRude/Elite-Dangerous-AI-Integration/blob/a31ed8a8bf26b6dbde19c6b45ed58e5decfcad07/src/lib/STT.py#L32

**Comment by RatherRude** [comment]
We added an action in the latest release that allows COVAS to open the galaxy map and enter a system name. I see this whisper hallucination creating issues.
I will change it to something less alarming. We will still need to give it some Elite-themed examples so it primes the whisper STT model for Elite and Sci-Fi context, so it recognized e.g. "Frame-Shift Drive" and not "Friendship Drive" reliably.
Will tinker with the prompt and release and updated version.

**Comment by RatherRude** [comment]
[I turned this into a more general prompt](https://github.com/RatherRude/Elite-Dangerous-AI-Integration/commit/bf51199ea684b6a5ec211379a49205858345bf9e). One that, if should whisper hallucinate, doesn't prompt the ship computer to plot a route somewhere!
